fix(object): fix issue when data is an object
For some reason, json-patch works well with an array while the original data was set to a string (which was a logical bug in the `eventSource.addEventListener('data', function(e) {})`). The bug was found when the api returns a JSON object {...} and we get the error msg: 

```json-patch-duplex.js:490
                obj = obj[key];
                         ^

TypeError: Cannot read property '2' of undefined```